{% set name = "plumed" %}
{% set version = environ['VERSION'] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
# cannot link gsl on MacOS
    - gsl # [linux]
  run:
    - zlib
    - gsl # [linux]

test:
  # TODO. In principle these could be the official regtests.
  commands:
    - plumed info --root
    - plumed info --version
    - plumed info --long-version
    - $PREFIX/lib/plumed/plumed-runtime -h

about:
  home: http://www.plumed.org/
  license: LGPL
  license_file: COPYING.LESSER
  summary: 'Free energy calculations in molecular systems'
  description: >
    PLUMED is an open source library for free energy calculations in
    molecular systems which works together with some of the most
    popular molecular dynamics engines.
  doc_url: https://plumed.github.io/doc-v2.5/user-doc/html/index.html
  dev_url: https://github.com/plumed/plumed2

